# Generated by Django 2.2.1 on 2019-05-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player_profile',
            options={'ordering': ['sports']},
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='player_name',
            field=models.CharField(max_length=100, verbose_name='Player Name'),
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='sports',
            field=models.CharField(max_length=100, verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_profiles.Team_Profile', verbose_name='Team Name'),
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='year_level',
            field=models.IntegerField(verbose_name='Year Level'),
        ),
        migrations.AlterField(
            model_name='team_profile',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='team_profile',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email Adress'),
        ),
        migrations.AlterField(
            model_name='team_profile',
            name='rec_email',
            field=models.CharField(max_length=100, verbose_name='Recovery Email'),
        ),
        migrations.AlterField(
            model_name='team_profile',
            name='teamName',
            field=models.CharField(max_length=100, verbose_name='Team Name'),
        ),
    ]
