# Generated by Django 2.1.5 on 2019-05-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_profiles', '0002_auto_20190501_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
