# Generated by Django 2.1.5 on 2019-03-06 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 2, 33, 26, 757761)),
        ),
    ]
