# Generated by Django 2.1.5 on 2019-03-06 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190306_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 2, 36, 7, 176465, tzinfo=utc)),
        ),
    ]
