# Generated by Django 2.1.5 on 2019-03-06 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190306_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
