# Generated by Django 2.1.5 on 2019-03-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190306_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='Images/None/no-img.jpg', upload_to='Images/'),
        ),
    ]
