# Generated by Django 2.1.5 on 2019-03-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190306_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='Images/%Y/%m/%d/'),
        ),
    ]
