# Generated by Django 2.1.7 on 2019-03-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sport', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('win', models.CharField(max_length=100)),
                ('lose', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
    ]
