# Generated by Django 2.2.1 on 2019-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20190327_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['sport']},
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='lose',
            field=models.IntegerField(verbose_name='Loss'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='sport',
            field=models.CharField(max_length=100, verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='team',
            field=models.CharField(max_length=100, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='win',
            field=models.IntegerField(verbose_name='Win'),
        ),
    ]
