# Generated by Django 2.1.5 on 2019-03-31 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190401_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
