# Generated by Django 2.1.5 on 2019-04-03 05:43

from django.db import migrations, models
import django.utils.timezone
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190401_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, validators=[schedule.models.validate_date]),
        ),
    ]
