# Generated by Django 2.1.5 on 2019-04-05 04:35

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20190403_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='image2',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_and_time',
            field=models.DateField(blank=True, validators=[schedule.models.validate_date]),
        ),
    ]
