# Generated by Django 2.1.5 on 2019-04-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20190405_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Images/%Y/%m/%d/'),
        ),
    ]
