# Generated by Django 2.2.1 on 2019-05-01 12:27

from django.db import migrations, models
import django.utils.timezone
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_schedule_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date_and_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, validators=[schedule.models.validate_date], verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Images/%Y/%m/%d/', verbose_name='Team One Image'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Images/%Y/%m/%d/', verbose_name='Team Two Image'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sport',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teamOne',
            field=models.CharField(max_length=100, verbose_name='Team One'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teamTwo',
            field=models.CharField(max_length=100, verbose_name='Team Two'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='venue',
            field=models.CharField(max_length=100, verbose_name='Venue'),
        ),
    ]
